# Generated by Django 6.1 on 2026-08-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/services/'),
        ),
    ]
