# Generated by Django 6.1 on 2026-08-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_servicecategory_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
